#--------------------------------------------------------------------------------------------------
# See 'Readme.md' for information
#--------------------------------------------------------------------------------------------------
before_script:
  - git config --global http.proxy "${HTTP_PROXY}"
  - git config --global https.proxy "${HTTPS_PROXY}"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"
  - export http_proxy="${HTTP_PROXY}"
  - export https_proxy="${HTTPS_PROXY}"
  - export no_proxy="${NO_PROXY}"
  - export NO_PROXY="${NO_PROXY}"
  - export GITTAG=`git describe --tags --abbrev=0 2> /dev/null`
  - git config --list
  - env

stages:
  - build
  - test
  - scan

build:gta:
  stage: build
  image: tpm-devel
  tags:
    - tpm-devel
  script:
    - make all
  artifacts:
    paths:
      - "out/trustagent-*.bin"
      - "out/tagent"
    expire_in: 1 year

test:
  stage: test
  image: tpm-devel
  tags:
    - tpm-devel
  script:
    - make unit_test
  artifacts:
    paths:
      - "out/cover.html"      
      - "out/tagent"
    expire_in: 1 year


stylechecker:
  stage: scan
  only:
    - merge_requests
  image: tpm-devel
  tags:
    - tpm-devel
  script:
    - gofmt -l .
    - gofmt -l . | wc -l
    
checkmarx:
     stage: scan
     only:
    - merge_requests
     tags: 
        - docker-checkmarx
     allow_failure: true
     services:
         - docker:dind
     image:
      name: 10.105.168.81:5000/checkmarx:isecl
      entrypoint: ['']
    #  /app/cx-flow.jar
    # /home/CX/cx-flow.jar

     script:
        - cat ${CX_FLOW_CONFIG} > application.yml
        - |
            if [ "$CI_PIPELINE_SOURCE" == "merge_request_event" ]; then 
                java -jar /app/cx-flow.jar --spring.config.location=./application.yml \
                 --scan \
                 --cx-team="${CHECKMARX_TEAM}" \
                 --cx-project="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
                 --app="${CI_PROJECT_NAME}" \
                 --project-id=${CI_PROJECT_ID} \
                 --merge-id=${CI_MERGE_REQUEST_IID} \
                 --bug-tracker=GITLABMERGE \
                 --cx-flow.break-build=false \
                 --f=.
            else
                 java -jar /app/cx-flow.jar --spring.config.location=./application.yml \
                    --scan \
                    --cx-team="${CHECKMARX_TEAM}" \
                    --cx-project="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
                    --app="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}" \
                    --branch="${CI_COMMIT_REF_NAME}" \
                    --repo-name="${CI_PROJECT_NAME}" \
                    --namespace="${CI_PROJECT_NAMESPACE##*/}" \
                    --cx-flow.break-build=false \
                    --f=.
            fi
